# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/api"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    # Ignore major dependency upgrades
    ignore:
      - dependency-name: "*"
        update-types: ["version-updates:semver-major"]

  - package-ecosystem: "npm"
    directory: "/web"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    # Ignore major dependency upgrades
    ignore:
      - dependency-name: "*"
        update-types: ["version-updates:semver-major"]
