version: '3.6'

services:
  postgres132:
    image: postgis/postgis:11-3.2
    environment:
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_HOST: $POSTGRES_HOST
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_USER: $POSTGRES_USER
    volumes:
      - ./.volumes/postgres:/var/lib/postgresql/data
    ports:
      - $POSTGRES_PORT:5432
    restart: always
